manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.5.0
      import: app/west.yml
    - name: prospector-zmk-module
      remote: carrefinho
      revision: v0.5.0
  self:
    path: config
